name: dv360_excel_plugin
description: an Excel plugin web app for DV360
# version: 1.0.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_components: 0.14.0-alpha+1
  convert: ^2.1.1
  js: ^0.6.1+1
  html: ^0.14.0+3

dev_dependencies:
  angular_router: ^2.0.0-alpha
  angular_test: ^2.3.0
  build_runner: ^1.3.0
  build_test: ^0.10.0
  build_web_compilers: ^2.4.0
  effective_dart: ^1.0.0
  mockito: ^4.1.1
  pageloader: ^3.3.0
  pedantic: ^1.9.0
  test: ^1.6.0
